name: Notify Discord
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: get commit message
        id: get_commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "::set-output name=commit_message::$COMMIT_MESSAGE"
          echo "::set-output name=commit_author::$COMMIT_AUTHOR"
      
      - name: send webhook to discord
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"새로운 게시물이 올라왔어요: ${{ steps.get_commit_info.outputs.commit_message }}\", \"sender\": \"${{ steps.get_commit_info.outputs.commit_author }}\"}" \
               https://discord.com/api/webhooks/your-webhook-url
